title: Qianqian Zhou
#url: "https://qianqianzhou.com"
#baseurl: "/qianqianzhou"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/Zhouqianqian"
footer_text: "Page design by Qianqian Zhou"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Contact"
   link: "contact"
 - name: "Resume"
   link: "CV-Qianqian Zhou.pdf"